version: '3.9'

services:
  backend:
    image: python:3.11-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -lc "npm install && npm run dev"
    environment:
      - VITE_API_BASE=http://localhost:8000/api
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
